baseURL = "https://getsy.io"
languageCode = "en-us"
title = "Getsy"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = "UA-132384513-2"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[params]
    author = "omrllm"
    description = "An experimental laboratory"
    githubUsername = "omrllm"
    accent = "green"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 2 
      
[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 3    

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "/"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/agetsy"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "/"
    name = "reddit"
    weight = 3

[[menu.icon]]
		url = "/"
		name = "language"
		weigth = 4
